name: Build and Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn build

      - name: Export
        run: |
          yarn export

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: out
