name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]
        python-version: [3.5]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build and Publish
        run: yarn deploy
